### ISSUE TITLE
Erron at final step card addition

### ISSUE THREAD

**Issue by glebfeklistov** [tomavic/cordova-apple-wallet#23]
![image](https://user-images.githubusercontent.com/5002394/85986038-46404f80-b9f4-11ea-9bac-545d2b336008.png)

I passed payload to "completeAddPaymentPass" and get this exception in xcode when run on real device with real payload and real wallet.

What happend?

**Comment by tomavic** [comment]
What is your current used version?

**Comment by glebfeklistov** [comment]
Current version

**Comment by tomavic** [comment]
@glebfeklistov 

You may use the previous 3.2.0 till we got to finish the fix

**Comment by glebfeklistov** [comment]
Ok. I'll try today and return with result.

**Comment by tomavic** [comment]
@glebfeklistov Could you please update share what you have done, Is version 3.2.0 has no issue?

**Comment by glebfeklistov** [comment]
@glebfeklistov same result

**Comment by tomavic** [comment]
Could you please show what are your system information?

**Comment by tomavic** [comment]
@faugusztin Could you please check why this is happening?

**Comment by faugusztin** [comment]
EXC_BAD_ACCESS happens when either completionHandler is null, not valid anymore or is called multiple times (completion handlers in iOS are valid just for one use). For example there is a [20 second time limit](https://developer.apple.com/documentation/passkit/pkaddpaymentpassviewcontrollerdelegate/1615915-addpaymentpassviewcontroller) between getting the result of startAddPaymentPass and calling completeAddPaymentPass - if that doesn't happen, the card addition fails.

Not sure how well @glebfeklistov can do Objective C coding, to check what is called one could add NSLog statements to the code before the completionHandler call to see what completionHandler is set to (if it is set at all at moment of call), what request is set to, if it is called twice and so on. NSLog statements are visible in Console even for apps from TestFlight/App Store (open Xcode, Window>Devices and Simulators, select device with the app installed, click on Open Console, then filter the output according to name of your app).

Also just a sanity check one needs to satisfy all these requirements to test adding payment passes at all :

- can be tested only via Testflight
- minimum iOS version must be set to 10.3 or higher
- provisioning profile must include com.apple.developer.payment-pass-provisioning entitlement (manual step by Apple) and production entitlement file must include com.apple.developer.payment-pass-provisioning set to true - see 
[Enabling In-App Provisioning of Payment Cards](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/ApplePayandPassKitEntitlements/ApplePayandPassKitEntitlements.html#//apple_ref/doc/uid/TP40011195-CH7-SW4)

**Comment by tomavic** [comment]
@glebfeklistov I've showed the requirements for this plugin to work efficiently in the First paragraph in the README.md

If you still have issues we are happy to help. Thanks for your interest in our plugin.
