### ISSUE TITLE
Test checkCardEligibilityBySuffix

### ISSUE THREAD

**Issue by jsupport** [tomavic/cordova-apple-wallet#25]
How can i check that the card has been added to the wallet?
I added the card to the wallet using a plugin, but checkCardEligibilityBySuffix always returns true.

**Comment by faugusztin** [comment]
While it is not said directly at the passesOfType API method, the reason is explained at the documentation of the [passes](https://developer.apple.com/documentation/passkit/pkpasslibrary/1617109-passes) method:

> Your app only has access to certain passes, based on its entitlements. Passes that your app doesn’t have access to are not returned.

There are multiple reasons why you might not have access to the pass, but considering you added the card using this plugin, that rules out the issues at the application side (iOS entitlements and provisioning profile issues) and your issue is most likely the provisioning information from your card operator. See https://developer.apple.com/forums/thread/109968 (the associatedApplicationIdentifiers value).

**Comment by jsupport** [comment]
thanks @faugusztin
